window.foodQuestData = {
  foods: [
    {
      id: "ramen",
      name: "Ramen",
      region: "Tokyo",
      type: "Noodles",
      xp: 40,
      mark: "R",
      visual: "ramen",
      difficulty: "Easy",
      allergy: "Wheat, soy, egg may be included",
      phrase: "Ramen o hitotsu kudasai.",
      tip: "Look for ticket machines near the entrance at many ramen shops.",
      description: "A rich noodle quest with many local styles."
    },
    {
      id: "sushi",
      name: "Sushi",
      region: "Tokyo",
      type: "Seafood",
      xp: 50,
      mark: "S",
      visual: "sushi",
      difficulty: "Easy",
      allergy: "Fish, shellfish, soy",
      phrase: "Osusume no sushi wa nan desu ka?",
      tip: "Counter sushi is friendly if you order one or two pieces at a time.",
      description: "A classic Japan quest for fresh fish and rice."
    },
    {
      id: "takoyaki",
      name: "Takoyaki",
      region: "Osaka",
      type: "Street food",
      xp: 35,
      mark: "T",
      visual: "takoyaki",
      difficulty: "Easy",
      allergy: "Wheat, egg, octopus",
      phrase: "Takoyaki o hitotsu kudasai.",
      tip: "It is usually very hot inside, so wait a moment before eating.",
      description: "Crispy outside, soft inside, full Osaka energy."
    },
    {
      id: "okonomiyaki",
      name: "Okonomiyaki",
      region: "Osaka",
      type: "Street food",
      xp: 45,
      mark: "O",
      visual: "okonomiyaki",
      difficulty: "Normal",
      allergy: "Wheat, egg, seafood may be included",
      phrase: "Okonomiyaki o onegai shimasu.",
      tip: "Some restaurants cook it for you, others let you grill it at the table.",
      description: "A savory grill quest with sauce and toppings."
    },
    {
      id: "matcha",
      name: "Matcha Sweets",
      region: "Kyoto",
      type: "Dessert",
      xp: 30,
      mark: "M",
      visual: "matcha",
      difficulty: "Easy",
      allergy: "Milk, wheat may be included",
      phrase: "Matcha no sweets wa arimasu ka?",
      tip: "Kyoto cafes often have seasonal matcha parfaits and wagashi sets.",
      description: "A calm Kyoto dessert quest with green tea flavor."
    },
    {
      id: "yudofu",
      name: "Yudofu",
      region: "Kyoto",
      type: "Vegetarian",
      xp: 55,
      mark: "Y",
      visual: "yudofu",
      difficulty: "Normal",
      allergy: "Soy",
      phrase: "Yudofu o tabetai desu.",
      tip: "This is a gentle Kyoto option, but sauces may contain fish stock.",
      description: "A gentle tofu quest from temple food culture."
    },
    {
      id: "hakata-ramen",
      name: "Hakata Ramen",
      region: "Fukuoka",
      type: "Noodles",
      xp: 60,
      mark: "H",
      visual: "hakata",
      difficulty: "Normal",
      allergy: "Wheat, pork, soy",
      phrase: "Kaedama dekimasu ka?",
      tip: "In Hakata, kaedama means an extra serving of noodles.",
      description: "A tonkotsu ramen quest from Fukuoka's yatai culture."
    },
    {
      id: "seafood-bowl",
      name: "Seafood Bowl",
      region: "Hokkaido",
      type: "Seafood",
      xp: 65,
      mark: "B",
      visual: "seafood",
      difficulty: "Hard",
      allergy: "Fish, shellfish, roe",
      phrase: "Kaisen-don o hitotsu kudasai.",
      tip: "Morning markets are a great place to try this in Hokkaido.",
      description: "A northern seafood quest with fresh local toppings."
    },
    {
      id: "miso-katsu",
      name: "Miso Katsu",
      region: "Nagoya",
      type: "Street food",
      xp: 55,
      mark: "K",
      visual: "grill",
      difficulty: "Normal",
      allergy: "Wheat, pork, soy",
      phrase: "Miso katsu o hitotsu kudasai.",
      tip: "Nagoya's red miso sauce is rich, sweet, and stronger than regular tonkatsu sauce.",
      description: "A Nagoya quest featuring crispy pork cutlet with deep red miso sauce."
    },
    {
      id: "hitsumabushi",
      name: "Hitsumabushi",
      region: "Nagoya",
      type: "Seafood",
      xp: 75,
      mark: "U",
      visual: "rice",
      difficulty: "Hard",
      allergy: "Fish, soy, wheat may be included",
      phrase: "Hitsumabushi o tabetai desu.",
      tip: "Try it three ways: plain, with toppings, and with warm broth.",
      description: "A grilled eel rice quest with a special Nagoya-style eating ritual."
    },
    {
      id: "okinawa-soba",
      name: "Okinawa Soba",
      region: "Okinawa",
      type: "Noodles",
      xp: 55,
      mark: "N",
      visual: "ramen",
      difficulty: "Easy",
      allergy: "Wheat, pork, soy",
      phrase: "Okinawa soba o hitotsu kudasai.",
      tip: "Despite the name, Okinawa soba uses wheat noodles instead of buckwheat noodles.",
      description: "A tropical noodle quest with pork, broth, and Okinawan comfort-food flavor."
    },
    {
      id: "goya-champuru",
      name: "Goya Champuru",
      region: "Okinawa",
      type: "Vegetarian",
      xp: 50,
      mark: "G",
      visual: "yudofu",
      difficulty: "Normal",
      allergy: "Egg, soy, pork may be included",
      phrase: "Goya champuru wa arimasu ka?",
      tip: "Goya is bitter melon, so this dish is a good challenge for adventurous travelers.",
      description: "An Okinawan stir-fry quest with bitter melon, tofu, egg, and local flavor."
    },
    {
      id: "hiroshima-okonomiyaki",
      name: "Hiroshima Okonomiyaki",
      region: "Hiroshima",
      type: "Street food",
      xp: 65,
      mark: "H",
      visual: "okonomiyaki",
      difficulty: "Normal",
      allergy: "Wheat, egg, seafood may be included",
      phrase: "Hiroshima okonomiyaki o onegai shimasu.",
      tip: "Hiroshima-style okonomiyaki is layered and often includes noodles.",
      description: "A layered okonomiyaki quest with cabbage, sauce, and noodles."
    },
    {
      id: "gyutan",
      name: "Gyutan",
      region: "Sendai",
      type: "Street food",
      xp: 70,
      mark: "B",
      visual: "grill",
      difficulty: "Hard",
      allergy: "Beef, soy may be included",
      phrase: "Gyutan teishoku o hitotsu kudasai.",
      tip: "Sendai gyutan is often served as a set meal with rice and soup.",
      description: "A Sendai quest for grilled beef tongue with smoky, savory flavor."
    }
  ]
};
